package rs.ac.uns.ftn.Bookify.enumerations;

import org.springframework.security.access.prepost.PreAuthorize;

public enum Privilege {
    VIEW_ACCOMMODATION_PRICE,
    VIEW_OWNER_ACCOMMODATIONS,
    FAVORITES,
    MANAGE_ACCOMMODATIONS,
    MANAGE_ACCOMMODATION_REQUEST,
    VIEW_CHARTS,
    MANAGE_NOTIFICATIONS,
    VIEW_OWNER_RESERVATION,
    VIEW_GUEST_RESERVATION,
    MODIFY_GUEST_RESERVATION,
    MODIFY_OWNER_RESERVATION,
    MANAGE_REVIEWS,
    WRITE_REVIEW_FOR_ACCOMMODATION,
    WRITE_REVIEW_FOR_OWNER,
    DELETE_REVIEW,
    REPORT_REVIEW,
    MANAGE_USERS,
    MANAGE_ACCOUNT,
    WRITE_REPORT,
    CERTIFICATE
}
